### ISSUE TITLE
Update register success email due to new deployment

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-email#55]
New [update](https://docs.google.com/document/d/1x_v6U-w-ZNa-QDMUXBJ1iSxcRy240D-Zjk0vLv9JPB4/edit) to email template.

**Comment by proformatters** [comment]
fixed successfully on desktop, iPhone and ipad

**Comment by proformatters** [comment]
![image](https://user-images.githubusercontent.com/47885618/97845174-38466680-1d27-11eb-9b85-fe0dc89f26ef.png)
A period should be added after the last sentence
